### ISSUE TITLE
Invalid path to the swagger-editor

### ISSUE THREAD

**Issue by tralves** [moander/node-swagger-editor-cli#1]
Hi! I installed and got the error:

``` fs.js:565
fs.write = function(fd, buffer, offset, length, position, callback) {
                                                 ^
Error: ENOENT, no such file or directory '/usr/local/lib/node_modules/swagger-editor-cli/node_modules/serve-swagger-editor/node_modules/swagger-editor/config/defaults.json'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/swagger-editor-cli/node_modules/serve-swagger-editor/lib/serve-swagger-editor.js:15:32)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/swagger-editor-cli/node_modules/serve-swagger-editor/index.js:3:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

The docs are a bit confusing because they say to install another package (`serve-swagger-editor`). I tried with and without installing that package, and installing `swagger-editor-cli` both local and globally. Nothing worked :(

**Comment by moander** [comment]
This package is deprecated. The swagger team have created a much better replacement.

Please try this:

```
npm install -g swagger

swagger project create hello-world

cd hello-world

swagger project edit
```

**Comment by tralves** [comment]
Thanks for the reply!
